#pragma once

#define WIFI_SSID "NTO_MGBOT_CITY"
#define WIFI_PASS "CHANGE_ME"

#define LOCAL_SERVER_BASE "http://192.168.31.63:8080"
#define DEVICE_ID "np2-01"
#define DEVICE_KIND "nav_point_type2"
#define HEARTBEAT_INTERVAL_MS 5000
#define COMMAND_POLL_INTERVAL_MS 1200
#define DUPLICATE_SUPPRESS_MS 2000

#define LED_PIN 4
#define LED_COUNT 16

